name: Deploy-Demo

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: archive files
        run: |
          mkdir ./archives
          ls
          cd ./CPSSVOperationTimeService
          zip -rq ../archives/CPSSVOperationTimeService.zip ./*

      - name: upload files for S3
        run: |
          ls
          aws s3 cp ./archives/CPSSVOperationTimeService.zip  s3://dev-nakano-testdata/

      - name: set files for lambda
        run: |
          aws lambda update-function-code --function-name CPSSVOperationTimeService_nakano --s3-bucket dev-nakano-testdata  --s3-key CPSSVOperationTimeService.zip --publish


      